// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqpocvswrtqntlomdyzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcG9jdnN3cnRxbnRsb21keXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzQxMDYsImV4cCI6MjA4ODI1MDEwNn0.w3DoUs-_xtQUhSxckXu4Pyl2Lbn13iw_OasFJfxHcUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});